"""Add team invitations table

Revision ID: e6fd146f7782
Revises: 76b639c9666e
Create Date: 2025-09-29 03:05:05.045840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fd146f7782'
down_revision = '76b639c9666e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'team_id', 'status', name='unique_pending_invitation')
    )
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.create_index('idx_invitation_email_status', ['email', 'status'], unique=False)
        batch_op.create_index('idx_invitation_token_status', ['token', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_email'))
        batch_op.drop_index('idx_invitation_token_status')
        batch_op.drop_index('idx_invitation_email_status')

    op.drop_table('team_invitations')
    # ### end Alembic commands ###
